version: '2'
services:
    app:
        working_dir: /app
        build: .
        volumes:
            - .:/app
        depends_on:
            - redis
    redis:
        image: redis
        volumes:
            - redis-data:/var/lib/redis
    nginx:
        image: nginx
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8081:80"