version: '2.1'
services:
    app:
        working_dir: /code
        build: .
        volumes:
            - .:/code
        depends_on:
            - redis
    redis:
        image: redis:alpine
        volumes:
            - redis-data:/var/lib/redis
    nginx:
        image: nginx
        links: 
            - app
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d
        ports:
            - "8081:80"
volumes:
    redis-data:
        driver: local