version: '2.1'
services:
    app:
        working_dir: /app
        build: .
        volumes:
            - .:/app
        depends_on:
            - redis
    redis:
        image: "redis:alpine"
        volumes:
            - redis-data:/var/lib/redis
    nginx:
        image: nginx
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8081:80"
volumes: 
    redis-data: {}